/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WStudentMain.java
 *
 * Created on Jan 21, 2011, 9:45:04 PM
 */

package mysd.student.services;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import mysd.DBSystem;

/**
 *
 * @author salam
 */
public class WStudentMain extends javax.swing.JFrame {

    /** Creates new form WStudentMain */
    public WStudentMain() {
        initComponents();
        loadData();
    }


    public void loadData(){

        String query = "SELECT STUDENT_ID, FULL_NAME, DATE_OF_BIRTH,"
                + "GENDER, FATHER_NAME, MOTHER_NAME FROM STUDENT "
                + "ORDER BY STUDENT_ID DESC LIMIT 2";
        
        DBSystem dbs = new DBSystem();
        Connection con = dbs.getConnection();

        Statement stmt = null;
        ResultSet rs = null;

        DefaultTableModel model = (DefaultTableModel)tblStudent.getModel();
        model.setRowCount(0);

        try
        {
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            
            while(rs.next()){
                
                Vector v = new Vector();
                v.add(rs.getString("STUDENT_ID"));
                v.add(rs.getString("FULL_NAME"));
                v.add(rs.getString("DATE_OF_BIRTH"));
                v.add(rs.getString("GENDER"));
                v.add(rs.getString("FATHER_NAME"));
                v.add(rs.getString("MOTHER_NAME"));
                
                model.addRow(v);
            }

            dbs.closeConnection(con);
        }
        catch(Exception e)
        {
            dbs.closeConnection(con);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();
        btnContact = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnEnrollment = new javax.swing.JButton();
        btnVanInfo = new javax.swing.JButton();
        btnHealth = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taBasicInfo = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        taParent = new javax.swing.JEditorPane();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ST000001", "Sanaullah Khan", "01-01-2010", "Female", "Rizwan Khan Lalwani", "Naila Rizwan"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Date of Birth", "Gender", "Father Name", "Mother Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);
        tblStudent.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblStudent.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblStudent.getColumnModel().getColumn(3).setPreferredWidth(30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNew.setBackground(new java.awt.Color(204, 204, 204));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnAddress.setBackground(new java.awt.Color(204, 204, 204));
        btnAddress.setText("Address");
        btnAddress.setEnabled(false);

        btnContact.setBackground(new java.awt.Color(204, 204, 204));
        btnContact.setText("Contact");
        btnContact.setEnabled(false);

        btnHistory.setBackground(new java.awt.Color(204, 204, 204));
        btnHistory.setText("History");
        btnHistory.setEnabled(false);

        btnEnrollment.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollment.setText("Enrollment");
        btnEnrollment.setEnabled(false);

        btnVanInfo.setBackground(new java.awt.Color(204, 204, 204));
        btnVanInfo.setText("Van Info");
        btnVanInfo.setEnabled(false);

        btnHealth.setBackground(new java.awt.Color(204, 204, 204));
        btnHealth.setText("Health");
        btnHealth.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnrollment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVanInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHealth)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVanInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(null);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(lbImage, java.awt.BorderLayout.CENTER);

        jScrollPane2.setViewportView(jPanel1);

        jScrollPane3.setBorder(null);

        taBasicInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        taBasicInfo.setBorder(null);
        taBasicInfo.setContentType("text/html");
        taBasicInfo.setEditable(false);
        taBasicInfo.setFont(new java.awt.Font("Monospaced", 0, 12));
        jScrollPane3.setViewportView(taBasicInfo);

        jScrollPane4.setBorder(null);

        taParent.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        taParent.setBorder(null);
        taParent.setContentType("text/html");
        jScrollPane4.setViewportView(taParent);

        jTextField1.setEditable(false);
        jTextField1.setText("LAST 10 ROWS FETCHED ARE SHOWN IN THE TABLE ABOVE");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        // TODO add your handling code here:
        int clickCount = evt.getClickCount();
        if(clickCount == 2){
        int r = tblStudent.getSelectedRow();
        String studentID = (String)tblStudent.getValueAt(r, 0);
        editStudentMainRecord(studentID);
        }else if(clickCount == 1){
            int r = tblStudent.getSelectedRow();
            String studentID = (String)tblStudent.getValueAt(r, 0);
            setRecord(studentID);
        }
    }//GEN-LAST:event_tblStudentMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void editStudentMainRecord(String studentID){
        
    }

    public void setRecord(String studentID){
        
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WStudentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnAddress;
    protected javax.swing.JButton btnContact;
    protected javax.swing.JButton btnEnrollment;
    protected javax.swing.JButton btnHealth;
    protected javax.swing.JButton btnHistory;
    protected javax.swing.JButton btnNew;
    protected javax.swing.JButton btnVanInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    protected javax.swing.JLabel lbImage;
    protected javax.swing.JEditorPane taBasicInfo;
    protected javax.swing.JEditorPane taParent;
    protected javax.swing.JTable tblStudent;
    // End of variables declaration//GEN-END:variables

}
