/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FDiscountList.java
 *
 * Created on Feb 16, 2011, 11:59:37 AM
 */
package mysd.administration;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mysd.GeneralDB;

/**
 *
 * @author salam
 */
public class FDiscountList extends javax.swing.JFrame {

    private GeneralDB gdb;

    /** Creates new form FDiscountList */
    public FDiscountList() {
        initComponents();
        gdb = new GeneralDB();
        listDiscountee();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfStudentID = new acr.component.CAlphaNumericField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        tfDiscount = new acr.component.CIntegerField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDiscount = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Discount/Exemption from Fee"));

        jLabel1.setText("Student ID");

        tfStudentID.setCharacter_limit(7);
        tfStudentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfStudentIDFocusLost(evt);
            }
        });

        jScrollPane1.setBorder(null);

        taInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        taInfo.setBorder(null);
        taInfo.setEditable(false);
        taInfo.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        taInfo.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        taInfo.setEnabled(false);
        jScrollPane1.setViewportView(taInfo);

        jLabel2.setText("Percentage of Discount");

        tfDiscount.setCharacter_limit(3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save32.png"))); // NOI18N
        jButton1.setText("Save/Update");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove24.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblDiscount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student#", "Name", "Father", "Discount %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiscountMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDiscount);
        tblDiscount.getColumnModel().getColumn(0).setResizable(false);
        tblDiscount.getColumnModel().getColumn(0).setPreferredWidth(25);
        tblDiscount.getColumnModel().getColumn(1).setResizable(false);
        tblDiscount.getColumnModel().getColumn(2).setResizable(false);
        tblDiscount.getColumnModel().getColumn(3).setResizable(false);
        tblDiscount.getColumnModel().getColumn(3).setPreferredWidth(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfStudentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStudentIDFocusLost
        // TODO add your handling code here:
        getStudentRecord(tfStudentID.getText());
    }//GEN-LAST:event_tfStudentIDFocusLost

    private void tblDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiscountMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblDiscount.getSelectedRow();
        if (selectedRow == -1) {
            ;
        } else {
            String studentID = (String) tblDiscount.getValueAt(selectedRow, 0);
            tfStudentID.setText(studentID);
            getStudentRecord(studentID);
            String discount = (String) tblDiscount.getValueAt(selectedRow, 3);
            tfDiscount.setText(discount);
        }
    }//GEN-LAST:event_tblDiscountMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveRecord();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDiscount.getSelectedRow();
        if (selectedRow == -1) {
            ;
        } else {
            String studentID = (String) tblDiscount.getValueAt(selectedRow, 0);
            tfStudentID.setText(studentID);
            getStudentRecord(studentID);
            String discount = (String) tblDiscount.getValueAt(selectedRow, 3);
            tfDiscount.setText(discount);
            this.removeDiscount(studentID);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void saveRecord() {
        String studentID = tfStudentID.getText();
        if (studentID == null || studentID.compareTo("") == 0) {
            ;
        } else {

            String discountPercent = tfDiscount.getText();
            boolean isCorrect = true;
            double discount = 0;
            try {
                discount = Double.parseDouble(discountPercent);
                if (discount > 100 || discount < 0) {
                    JOptionPane.showMessageDialog(null, "Discount must not exceed 100");
                    isCorrect = false;
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Please enter correct number");
                isCorrect = false;
            }

            if (isCorrect == true) {
                String query = "REPLACE INTO STUDENTDISCOUNT(STUDENTID, DISCOUNTPERCENT)"
                        + " VALUES("
                        + "'" + studentID + "',"
                        + "'" + discountPercent + "')";
                String msg = gdb.execute(query);
                if(msg.compareToIgnoreCase("ok")==0){
                    JOptionPane.showMessageDialog(null, "Record saved");
                    listDiscountee();
                }else{
                    JOptionPane.showMessageDialog(null, msg);
                }
            }
        }
    }


    public void listDiscountee(){

        DefaultTableModel model = (DefaultTableModel)tblDiscount.getModel();
        model.setRowCount(0);

        String query = "SELECT STUDENTID, DISCOUNTPERCENT FROM "
                + "STUDENTDISCOUNT";
        ArrayList al = gdb.searchRecord(query);
        Iterator i = al.iterator();
        while(i.hasNext()){
            Vector v = (Vector)i.next();
            String studentID = (String)v.get(0);
            String discount = (String)v.get(1);

            String Nquery = "SELECT FULL_NAME, FATHER_NAME FROM "
                    + "STUDENT WHERE STUDENT_ID LIKE '"+studentID+"'";
            Vector nv = gdb.getSingleRow(Nquery);
            String name = (String)nv.get(0);
            String fname = (String)nv.get(1);

            Vector row = new Vector();
            row.add(studentID);
            row.add(name);
            row.add(fname);
            row.add(discount);

            model.addRow(row);
        }
    }


    public void removeDiscount(String studentID){
        int answer = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to cease discount for selected student?",
                null,
                JOptionPane.YES_NO_CANCEL_OPTION);

        if(answer == JOptionPane.YES_OPTION){
            String query = "DELETE FROM STUDENTDISCOUNT WHERE STUDENTID LIKE "
                    + "'"+studentID+"'";
            gdb.execute(query);
            listDiscountee();
        }
    }

    public void getStudentRecord(String studentID) {
        String query = "SELECT FULL_NAME, FATHER_NAME, DATE_OF_BIRTH FROM "
                + "STUDENT WHERE STUDENT_ID LIKE '" + studentID + "'";
        Vector v = gdb.getSingleRow(query);

        if (v != null || v.size() != 0) {
            String name = (String) v.get(0);
            String fatherName = (String) v.get(1);
            String dob = (String) v.get(2);

            String str = "Name: " + name + "\n";
            str += "Father Name: " + fatherName + "\n";
            str += "Date of Birth: " + dob + "\n";

            taInfo.setText(str);

        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FDiscountList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JEditorPane taInfo;
    private javax.swing.JTable tblDiscount;
    private acr.component.CIntegerField tfDiscount;
    private acr.component.CAlphaNumericField tfStudentID;
    // End of variables declaration//GEN-END:variables
}
