/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FSpace.java
 *
 * Created on Jan 28, 2011, 5:52:59 PM
 */

package mysd.administration;

/**
 *
 * @author salam
 */
public class FSpace extends javax.swing.JFrame {

    /** Creates new form FSpace */
    public FSpace() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuilding = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClasses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBuilding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Building ID", "Name", "Description", "Units"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBuilding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuildingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuilding);
        tblBuilding.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblBuilding.getColumnModel().getColumn(1).setPreferredWidth(10);
        tblBuilding.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblBuilding.getColumnModel().getColumn(3).setPreferredWidth(10);

        tblClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Campus ID", "Room #", "Description", "Com#"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClassesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClasses);
        tblClasses.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblClasses.getColumnModel().getColumn(2).setPreferredWidth(10);
        tblClasses.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblClasses.getColumnModel().getColumn(4).setPreferredWidth(10);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Availiable Campuses/Buildings in Space");

        jLabel2.setText("Single click on the row to view classes in the campus. To edit campus record double click on row");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setText("Availiable Rooms in Selected Campus");

        jLabel4.setText("Double Click to edit/update the information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBuildingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuildingMouseClicked
        // TODO add your handling code here:
        int clickCount = evt.getClickCount();
        if(clickCount == 1){
            int selectedRow = tblBuilding.getSelectedRow();
            String buildingID = (String)tblBuilding.getValueAt(selectedRow, 0);
            showClassRoomInfo(buildingID);
        }else if(clickCount == 2){
            int selectedRow = tblBuilding.getSelectedRow();
            String buildingID = (String)tblBuilding.getValueAt(selectedRow, 0);
            updateBuildingRecord(buildingID);
        }
    }//GEN-LAST:event_tblBuildingMouseClicked

    private void tblClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClassesMouseClicked
        // TODO add your handling code here:
        int clickCount = evt.getClickCount();
        if(clickCount == 2){
            updateClassRoomRecord();
        }
    }//GEN-LAST:event_tblClassesMouseClicked

    public void updateBuildingRecord(String buildingID){
        
    }
    
    public void updateClassRoomRecord(){
        
    }
    
    public void showClassRoomInfo(String buildingID){
        
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSpace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JTable tblBuilding;
    protected javax.swing.JTable tblClasses;
    // End of variables declaration//GEN-END:variables

}
