/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FStudentAttendence.java
 *
 * Created on Jan 30, 2011, 7:45:28 PM
 */
package mysd.attendence;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import mysd.GeneralDB;

/**
 *
 * @author salam
 */
public class FStudentAttendence extends javax.swing.JFrame {

    /** Creates new form FStudentAttendence */
    public FStudentAttendence() {
        initComponents();
        setLocationRelativeTo(null);
        //getContentPane().setBackground(Color.darkGray);
    }

     public FStudentAttendence(String studentID) {
        initComponents();
        setLocationRelativeTo(null);
        this.tfStudentID.setText(studentID);
        setStudentInfo(tfStudentID.getText());
        //getContentPane().setBackground(Color.darkGray);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendence = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tfDateTo = new acr.component.CDateField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDateFrom = new acr.component.CDateField();
        tfStudentID = new acr.component.CAlphaNumericField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfTotalWorkingDays = new acr.component.CIntegerField();
        jLabel7 = new javax.swing.JLabel();
        tfTotalDaysPresent = new acr.component.CIntegerField();
        jLabel8 = new javax.swing.JLabel();
        tfTotalDaysNotPresent = new acr.component.CIntegerField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        tfFatherName = new javax.swing.JTextField();
        tfDateOfBirth = new javax.swing.JTextField();
        tfGrade = new javax.swing.JTextField();
        tfRoomID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfCStatus = new javax.swing.JTextField();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student attendence record");
        setResizable(false);

        tblAttendence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Day", "Status", "Description"
            }
        ));
        jScrollPane1.setViewportView(tblAttendence);
        tblAttendence.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblAttendence.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblAttendence.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblAttendence.getColumnModel().getColumn(3).setPreferredWidth(200);

        tfDateTo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Date (From)");

        jLabel3.setText("Date (To)");

        tfDateFrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfStudentID.setEditable(false);
        tfStudentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStudentID.setEnabled(false);
        tfStudentID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfStudentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfStudentIDFocusLost(evt);
            }
        });

        jLabel1.setText("Student ID");

        jButton1.setText("Get");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfStudentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(tfDateTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(tfDateFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Total Working Days");

        tfTotalWorkingDays.setEditable(false);
        tfTotalWorkingDays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotalWorkingDays.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfTotalWorkingDays.setEnabled(false);
        tfTotalWorkingDays.setFont(new java.awt.Font("Dialog", 1, 12));

        jLabel7.setText("Total Days (Present)");

        tfTotalDaysPresent.setEditable(false);
        tfTotalDaysPresent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotalDaysPresent.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfTotalDaysPresent.setEnabled(false);
        tfTotalDaysPresent.setFont(new java.awt.Font("Dialog", 1, 12));

        jLabel8.setText("Total Days (Not Present)");

        tfTotalDaysNotPresent.setEditable(false);
        tfTotalDaysNotPresent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotalDaysNotPresent.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfTotalDaysNotPresent.setEnabled(false);
        tfTotalDaysNotPresent.setFont(new java.awt.Font("Dialog", 1, 12));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalDaysNotPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotalDaysPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotalWorkingDays, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalWorkingDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalDaysPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalDaysNotPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton3.setText("Build Report");

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Dialog", 1, 12));
        tfName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfName.setBorder(null);
        tfName.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfName.setEnabled(false);

        tfFatherName.setEditable(false);
        tfFatherName.setFont(new java.awt.Font("Dialog", 1, 12));
        tfFatherName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFatherName.setBorder(null);
        tfFatherName.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfFatherName.setEnabled(false);

        tfDateOfBirth.setEditable(false);
        tfDateOfBirth.setFont(new java.awt.Font("Dialog", 1, 12));
        tfDateOfBirth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfDateOfBirth.setBorder(null);
        tfDateOfBirth.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfDateOfBirth.setEnabled(false);

        tfGrade.setEditable(false);
        tfGrade.setFont(new java.awt.Font("Dialog", 1, 12));
        tfGrade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfGrade.setBorder(null);
        tfGrade.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfGrade.setEnabled(false);

        tfRoomID.setEditable(false);
        tfRoomID.setFont(new java.awt.Font("Dialog", 1, 12));
        tfRoomID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfRoomID.setBorder(null);
        tfRoomID.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfRoomID.setEnabled(false);

        jLabel4.setText("Name");

        jLabel5.setText("Father Name");

        jLabel9.setText("Date of Birth");

        jLabel10.setText("Grade/Class");

        jLabel11.setText("Room ID");

        tfCStatus.setEditable(false);
        tfCStatus.setFont(new java.awt.Font("Dialog", 1, 12));
        tfCStatus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfCStatus.setBorder(null);
        tfCStatus.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfCStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(tfCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String studentID = tfStudentID.getText();
        String dateFrom = tfDateFrom.getSQLDate();
        String dateTo = tfDateTo.getSQLDate();

        fetchAttendence(studentID, dateFrom, dateTo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfStudentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStudentIDFocusLost
        // TODO add your handling code here:
        setStudentInfo(tfStudentID.getText());
    }//GEN-LAST:event_tfStudentIDFocusLost

    public void setStudentInfo(String studentID){
        String query = "SELECT FULL_NAME, FATHER_NAME, DATE_OF_BIRTH FROM "
                + "STUDENT WHERE STUDENT_ID LIKE '"+studentID+"'";
        Vector v = GeneralDB.getSingleRow(query);
        tfName.setText((String)v.get(0));
        tfFatherName.setText((String)v.get(1));
        tfDateOfBirth.setText((String)v.get(2));

        query = "SELECT GRADEID, CLASSROOMID, CSTATUS FROM "
                + "CURRENTENROLLMENT WHERE STUDENTID LIKE '"+studentID+"'";

        v = GeneralDB.getSingleRow(query);
        tfGrade.setText((String)v.get(0));
        tfRoomID.setText((String)v.get(1));
        tfCStatus.setText((String)v.get(2));
        
    }


    public void fetchAttendence(String studentID,
            String dateFrom, String dateTo) {

        
        DefaultTableModel model = (DefaultTableModel) tblAttendence.getModel();
        model.setRowCount(0);

        String query = "SELECT ATTENDENCE_DATE, ATTENDENCE_STATE "
                + "FROM STUDENTATTENDENCE WHERE "
                + "STUDENTID LIKE '" + studentID + "'"
                + " AND ATTENDENCE_DATE BETWEEN "
                + "'" + dateFrom + "' AND '" + dateTo + "'";

        GeneralDB gdb = new GeneralDB();
        ArrayList al = gdb.searchRecord(query);
        Iterator i = al.iterator();
        
        while (i.hasNext()) {
            Vector v = (Vector) i.next();
            String atDate = (String) v.get(0);
            String atState = (String) v.get(1);

            //fetch description of the attendence code
            String sQuery = "SELECT ATDESCRIPTION FROM "
                    + "ATTENDENCE_STATE WHERE "
                    + "ATCODE LIKE '" + atState + "'";

            String atDesc = gdb.getSingleColumnData(sQuery);
            System.out.println(atDesc);

            //get day name from a date

            String day = "";
            if (atDate != null || !(atDate.length() < 2)) {
                
                String[] toke = atDate.split("-");
                String yr = toke[0];
                String mn = toke[1];
                String dd = toke[2];

                int year = Integer.parseInt(yr);
                int month = Integer.parseInt(mn);
                int ddd = Integer.parseInt(dd);

                Date d = (new GregorianCalendar(year, month, ddd)).getTime();
                day = new SimpleDateFormat("EEEE").format(d);

            }

            Vector row = new Vector();
            row.add(atDate);
            row.add(day);
            row.add(atState);
            row.add(atDesc);
            model.addRow(row);
        }

        query = "SELECT DISTINCT ATTENDENCE_DATE "
                + "FROM STUDENTATTENDENCE WHERE "
                + " ATTENDENCE_DATE BETWEEN '"+dateFrom+"' AND "
                + "'"+dateTo+"'";

        ArrayList bl = gdb.searchRecord(query);
        String workingDays = "0";
        workingDays = Integer.toString(bl.size());
        

        tfTotalWorkingDays.setText(workingDays);
        
        query = "SELECT COUNT(*) FROM STUDENTATTENDENCE WHERE "
                + " ATTENDENCE_DATE BETWEEN '"+dateFrom+"' AND "
                + "'"+dateTo+"' AND (ATTENDENCE_STATE "
                + "LIKE 'PRESENT') AND STUDENTID LIKE "
                + "'"+studentID+"'";

        tfTotalDaysPresent.setText(gdb.getSingleColumnData(query));
        
        query = "SELECT COUNT(*) FROM STUDENTATTENDENCE WHERE "
                + " ATTENDENCE_DATE BETWEEN '"+dateFrom+"' AND "
                + "'"+dateTo+"' AND ATTENDENCE_STATE "
                + "NOT LIKE ('PRESENT') AND STUDENTID LIKE "
                + "'"+studentID+"'";

        tfTotalDaysNotPresent.setText(gdb.getSingleColumnData(query));



    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FStudentAttendence().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblAttendence;
    private javax.swing.JTextField tfCStatus;
    private acr.component.CDateField tfDateFrom;
    private javax.swing.JTextField tfDateOfBirth;
    private acr.component.CDateField tfDateTo;
    private javax.swing.JTextField tfFatherName;
    private javax.swing.JTextField tfGrade;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRoomID;
    private acr.component.CAlphaNumericField tfStudentID;
    private acr.component.CIntegerField tfTotalDaysNotPresent;
    private acr.component.CIntegerField tfTotalDaysPresent;
    private acr.component.CIntegerField tfTotalWorkingDays;
    // End of variables declaration//GEN-END:variables
}
