/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FInvoiceSimpleView.java
 *
 * Created on Mar 3, 2011, 6:11:51 PM
 */

package mysd.fee;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import mysd.GeneralDB;

/**
 *
 * @author salam
 */
public class FInvoiceSimpleView extends javax.swing.JFrame {

    private GeneralDB gdb;
    /** Creates new form FInvoiceSimpleView */
    public FInvoiceSimpleView(String invoiceID) {
        initComponents();
        setLocationRelativeTo(null);
        gdb = new GeneralDB();
        getInvoiceDetails(invoiceID);
    }

    public void getInvoiceDetails(String invoiceID){
        String query = "SELECT STUDENT_ID, GRADE_ID, TIME_CODE,"
                + "ISSUE_DATE, DUE_DATE, INVOICE_TOTAL, INVOICE_STATUS,"
                + "DISCOUNT FROM MONTHLYINVOICEISSUED WHERE "
                + "INVOICE_ID LIKE '"+invoiceID+"'";

        Vector v = gdb.getSingleRow(query);
        String studentID = (String)v.get(0);
        String gradeID = (String)v.get(1);
        String timeCode = (String)v.get(2);
        String issueDate = (String)v.get(3);
        String dueDate = (String)v.get(4);
        String invoiceTotal = (String)v.get(5);
        String invoiceStatus = (String)v.get(6);
        String discount = (String)v.get(7);

        query = "SELECT FULL_NAME, FATHER_NAME, DATE_OF_BIRTH FROM "
                + "STUDENT WHERE STUDENT_ID LIKE '"+studentID+"'";

        Vector p = gdb.getSingleRow(query);
        String name = (String)p.get(0);
        String fatherName = (String)p.get(1);
        String dateOfBirth = (String)p.get(2);

        String str = "";
        str+="STUDENT ID     :"+studentID+"\n";
        str+="NAME           :"+name+"\n";
        str+="FATHER NAME    :"+fatherName+"\n";
        str+="DATE OF BIRTH  :"+dateOfBirth+"\n";
        str+="GRADE/CLASS    :"+gradeID+"\n";

        this.taStudentDetails.setText(str);

        String strInvoiceInfo = "";
        strInvoiceInfo+="INVOICE MONTH     :"+timeCode+"\n";
        strInvoiceInfo+="ISSUE DATE        :"+issueDate+"\n";
        strInvoiceInfo+="DUE DATE          :"+dueDate+"\n";
        strInvoiceInfo+="DISCOUNT (%)      :"+discount+"\n";
        strInvoiceInfo+="INVOICE AMOUNT    :"+invoiceTotal+"\n";
        strInvoiceInfo+="STATUS OF INVOICE :"+invoiceStatus;

        this.taInvoiceDetails.setText(strInvoiceInfo);

        query = "SELECT FEE_CATEGORY, FEE_DETAILS, FEE_AMOUNT FROM "
                + "MONTHLYINVOICEDETAILSISSUED WHERE INVOICE_ID LIKE "
                + "'"+invoiceID+"'";
        ArrayList al = gdb.searchRecord(query);
        Iterator i = al.iterator();

        DefaultTableModel model = (DefaultTableModel)tblItems.getModel();
        model.setRowCount(0);

        
        while(i.hasNext()){
            Vector r = (Vector)i.next();
            model.addRow(r);
            
        }

        

        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taStudentDetails = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taInvoiceDetails = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        taStudentDetails.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        taStudentDetails.setColumns(20);
        taStudentDetails.setEditable(false);
        taStudentDetails.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        taStudentDetails.setRows(5);
        taStudentDetails.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        taStudentDetails.setEnabled(false);
        jScrollPane1.setViewportView(taStudentDetails);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        taInvoiceDetails.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        taInvoiceDetails.setColumns(20);
        taInvoiceDetails.setEditable(false);
        taInvoiceDetails.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        taInvoiceDetails.setRows(5);
        taInvoiceDetails.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        taInvoiceDetails.setEnabled(false);
        jScrollPane2.setViewportView(taInvoiceDetails);

        jScrollPane3.setBorder(null);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblItems);
        tblItems.getColumnModel().getColumn(0).setResizable(false);
        tblItems.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblItems.getColumnModel().getColumn(1).setResizable(false);
        tblItems.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblItems.getColumnModel().getColumn(2).setPreferredWidth(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInvoiceSimpleView("03201100004").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taInvoiceDetails;
    private javax.swing.JTextArea taStudentDetails;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables

}
