/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FPayment.java
 *
 * Created on Feb 28, 2011, 8:17:33 PM
 */

package mysd.fee;

import mysd.GeneralDB;
import mysd.Utils;

/**
 *
 * @author salam
 */
public class FPayment extends javax.swing.JFrame {

    private GeneralDB gdb;
    //private DefaultTableModel modelTBLInvoice;
    /** Creates new form FPayment */
    public FPayment() {
        initComponents();
        gdb = new GeneralDB();
        setLocationRelativeTo(null);
    }

    public FPayment(String invoiceID, String studentID) {
        initComponents();
        gdb = new GeneralDB();
        tfInvoiceID.setText(invoiceID);
        tfStudentID.setText(studentID);
        setLocationRelativeTo(null);
        this.setData(invoiceID, studentID);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfInvoiceID = new acr.component.CAlphaNumericField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfVoucherID = new acr.component.CAlphaNumericField();
        tfStudentID = new acr.component.CAlphaNumericField();
        jLabel5 = new javax.swing.JLabel();
        tfGradeID = new acr.component.CAlphaNumericField();
        jLabel6 = new javax.swing.JLabel();
        tfName = new acr.component.CTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPaymentDate = new acr.component.CDateField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbPaymentMethod = new javax.swing.JComboBox();
        cmbBankID = new javax.swing.JComboBox();
        tfPaymentAmount = new acr.component.CIntegerField();
        tfInstrumentNo = new acr.component.CAlphaNumericField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/StudentPayment32.png"))); // NOI18N
        jLabel1.setText("Fee Payment");

        jLabel2.setText("Invoice ID");

        tfInvoiceID.setEditable(false);
        tfInvoiceID.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfInvoiceID.setEnabled(false);
        tfInvoiceID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfInvoiceIDFocusLost(evt);
            }
        });

        jLabel3.setText("Voucher ID");

        tfVoucherID.setEditable(false);
        tfVoucherID.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfVoucherID.setEnabled(false);

        tfStudentID.setEditable(false);
        tfStudentID.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfStudentID.setEnabled(false);

        jLabel5.setText("Student #");

        tfGradeID.setEditable(false);
        tfGradeID.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfGradeID.setEnabled(false);

        jLabel6.setText("Grade ID");

        tfName.setEditable(false);
        tfName.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfName.setEnabled(false);

        jLabel7.setText("Name");

        jLabel10.setText("Date");

        tfPaymentDate.setEditable(false);
        tfPaymentDate.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfPaymentDate.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(tfVoucherID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGradeID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPaymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfVoucherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGradeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel8.setText("Payment Method");

        jLabel9.setText("Bank (Instrument)");

        jLabel11.setText("Payment Amount");

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CASH", "BANK" }));

        cmbBankID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfPaymentAmount.setEditable(false);
        tfPaymentAmount.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        tfPaymentAmount.setEnabled(false);

        jLabel12.setText("Bank ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfInstrumentNo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(cmbPaymentMethod, 0, 137, Short.MAX_VALUE)
                    .addComponent(cmbBankID, javax.swing.GroupLayout.Alignment.TRAILING, 0, 137, Short.MAX_VALUE)
                    .addComponent(tfPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBankID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfInstrumentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save32.png"))); // NOI18N
        jButton1.setText("Pay");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfInvoiceIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInvoiceIDFocusLost
        // TODO add your handling code here:
        //getUnpaidInvoices(invoiceID.getText());
    }//GEN-LAST:event_tfInvoiceIDFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String invoiceID = tfInvoiceID.getText();
        this.payInvoice(invoiceID);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setData(String invoiceID, String studentID){
        tfVoucherID.setText(this.prepareVoucherID(invoiceID));
        tfStudentID.setText(studentID);
        tfGradeID.setText(this.getCurrentGrade(studentID));
        tfName.setText(this.getStudentName(studentID));
        tfPaymentDate.setNormalDate(gdb.getCurrentDate());
        tfPaymentAmount.setText(this.getInvoiceAmount(invoiceID));
    }
    
    public void payInvoice(String invoiceID){
        
        String voucherID = tfVoucherID.getText();
        String studentID = tfStudentID.getText();
        String gradeID = tfGradeID.getText();
        String studentName = tfName.getText();
        String paymentMethod = (String)cmbPaymentMethod.getSelectedItem();
        String bankID = (String)cmbBankID.getSelectedItem();
        String paymentDate = tfPaymentDate.getSQLDate();
        String paymentAmount = tfPaymentAmount.getText();
        String userID = System.getProperty("LOGIN_USER_NAME");
        String ttime = gdb.getTimeStamp();
        String instrumentNo = tfInstrumentNo.getText();
        String timeCode = invoiceID.substring(0, 6);

        String query = "REPLACE INTO PAYMENT(VOUCHERID, INVOICEID,"
                + "STUDENTID, GRADEID, STUDENTNAME, PAYMENTMETHOD,"
                + "INSTRUMENTNO, BANKID, PAYMENTDATE, PAYMENTAMOUNT,"
                + "USERID, TTIME, TIMECODE)VALUES("
                + "'"+voucherID+"',"
                + "'"+invoiceID+"',"
                + "'"+studentID+"',"
                + "'"+gradeID+"',"
                + "'"+studentName+"',"
                + "'"+paymentMethod+"',"
                + "'"+instrumentNo+"',"
                + "'"+bankID+"',"
                + "'"+paymentDate+"',"
                + "'"+paymentAmount+"',"
                + "'"+userID+"',"
                + "'"+ttime+"',"
                + "'"+timeCode+"'"
                + ")";

        String stats = gdb.execute(query);
        if(stats.compareToIgnoreCase("ok")==0){
            Utils.msg("Invoice paid successfully");
            this.setVisible(false);
            this.dispose();
        }else if(stats.startsWith("Duplicate")){
            Utils.msg("This invoice is already paid");
        }else{
            Utils.msg(stats);
        }

    }

    public String getInvoiceAmount(String invoiceID){
        
        String query = "SELECT INVOICE_TOTAL FROM MONTHLYINVOICEISSUED "
                + "WHERE INVOICE_ID LIKE '"+invoiceID+"'";
        
        String amount = gdb.getSingleColumnData(query);
        
        return amount;

    }

    public String getStudentName(String studentID){
        String name = "";
        String query = "SELECT FULL_NAME FROM STUDENT WHERE STUDENT_ID "
                + "LIKE '"+studentID+"'";
        name = gdb.getSingleColumnData(query);
        return name;
    }

    public String getCurrentGrade(String studentID){
        String currentGrade = "";
        String query = "SELECT GRADEID FROM CURRENTENROLLMENT WHERE "
                + "STUDENTID LIKE '"+studentID+"'";
        currentGrade = gdb.getSingleColumnData(query);
        return currentGrade;
    }

    public String prepareVoucherID(String invoiceID){
        String maxID = "0";
        String query = "SELECT MAX(ID) FROM PAYMENT";
        maxID = gdb.getSingleColumnData(query);
        if(maxID == null){
            maxID = "1";
        }
        String voucherID = invoiceID+maxID;
        return voucherID;
    }
//    public void getUnpaidInvoices(String studentID){
//        String query = "SELECT INVOICE_ID, ISSUE_DATE, DUE_DATE, "
//                + "INVOICE_TOTAL FROM mys.MONTHLYINVOICEISSUED WHERE "
//                + "STUDENT_ID LIKE '"+studentID+"'";
//
//        System.out.println(query);
//
//
//        modelTBLInvoice.setRowCount(0);
//
//        ArrayList al = gdb.searchRecord(query);
//        Iterator i = al.iterator();
//
//        while(i.hasNext()){
//            Vector v = (Vector)i.next();
//            String invoiceID = (String)v.get(0);
//            String issueDate = (String)v.get(1);
//            String dueDate = (String)v.get(2);
//            String invoiceTotal = (String)v.get(3);
//
//            Vector row = new Vector();
//            row.add(invoiceID);
//            row.add(issueDate);
//            row.add(dueDate);
//            row.add(invoiceTotal);
//
//            System.out.println(row.toString());
//
//            modelTBLInvoice.addRow(row);
//
//
//        }
//
//    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbBankID;
    private javax.swing.JComboBox cmbPaymentMethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private acr.component.CAlphaNumericField tfGradeID;
    private acr.component.CAlphaNumericField tfInstrumentNo;
    private acr.component.CAlphaNumericField tfInvoiceID;
    private acr.component.CTextField tfName;
    private acr.component.CIntegerField tfPaymentAmount;
    private acr.component.CDateField tfPaymentDate;
    private acr.component.CAlphaNumericField tfStudentID;
    private acr.component.CAlphaNumericField tfVoucherID;
    // End of variables declaration//GEN-END:variables

}
